### ISSUE TITLE
Why not use componentHandler instead ?

### ISSUE THREAD

**Issue by darkyen** [tleunen/react-mdl#1]
The wrapper is nice ! but i wonder why are you not using the way recommended for dynamic content generation by material design team ?

**Comment by darkyen** [comment]
the code can then simply become
```js
   componentDidMount(){
     let domNode = React.findDOMnode(this);
     let ch = componentHandler.upgradeElement(domNode);
   }
   componentWillUnmount(){
      ch.downgradeElement();
   }
```

**Comment by tleunen** [comment]
Good point. To be honest, I never thought about their `upgradeComponent` function...
Sure it will work and as you said, it will simplifies a lot the code and will make sure the code stays in sync. But I don't like the fact the entire JS file will be required to make that work. The current MDL implementation is not really module friendly. Maybe that will change in the future.

With your code sample, i'd need to reset (downgrade - upgrade) when the component receive new props as well, at least for the textfield since it'll receive the `maxRows` at an attribute.

For complex components like the `layout`, it won't be possible though since I'll probably split them in multiple components (Layout, Header, Navigation, Tabs, Drawer).

Also, using the original JS code to upgrade the elements makes the code less "react friendly" since it creates dom nodes on the fly. I don't think it's a major issue though but still...

But I'm open to discussion...

**Comment by darkyen** [comment]
Not really when components are passed you can use the element.widget to update them :) using the api and selectively have it update and reMount on update that can be packed as a mixin or sebmecks higher order classes. Also about modularity that is indeed a. Bummer so far but as of now you need the file anyways and when modularity will come it should be a transparent update for the user ... Btw the credits to this idea goes to winjs team and also at the level of pure css and vanillajs enclosed high performance components the react magic is an overhead over extremely performant hand tweaked js code.

-----Original Message-----

**Comment by tleunen** [comment]
Currently, the master js file is not needed.

I'll investigate this path of including it and make the component just "container" calling the upgrade/downgrade function.
Not sure yet how to do for the Layout/Drawer though. Any idea?

**Comment by darkyen** [comment]
@tleunen For layouts I'd say a mix of both, you can listen to events and call React.render on individual props when you wish to dynamically render them out of react context but that will not be justice. I'd say use react to create the html and then call .upgrade.

Have a look at http://darkyen.github.io/react-ui-components/ 

It is a hybrid method of doing what you did.

**Comment by tleunen** [comment]
I'll make some tests this weekend using the component upgrade feature. I'll create a specific branch for that so you can see what I'm doing

**Comment by darkyen** [comment]
I'd love to help :-) , Then I can move basic components out of my ui-components and have only common app ones there.

**Comment by tleunen** [comment]
Tried something on this branch https://github.com/tleunen/react-mdl/tree/component-upgrade
What do you think?

**Comment by darkyen** [comment]
:D :D thats awesome !
 

Much better than my small implementation :D +1 + 1

**Comment by darkyen** [comment]
```
       var buttonClasses = classNames('mdl-button mdl-js-button', {
            'mdl-js-ripple-effect': ripple,
            'mdl-button--raised': raised,
            'mdl-button--colored': colored,
            'mdl-button--primary': primary,
            'mdl-button--accent': accent,
            'mdl-button--icon': !!icon
        }, className);
```

**Comment by tleunen** [comment]
I played a bit with my implementation and it had some issues. I cannot register the MDL components on the fly because the order of registered components inside MDL is important. I cannot register the Ripple Effect because Button (or Switch) for example.
So I'm removing that part, and until I find a better way (or MDL fixes this part), the MDL js file will be needed so we have the global `componentHandler` variable. I'll publish 0.5 with this change.

About inheritance vs helper class, I'll think about it. It won't make sense if it's not used a lot, so I'll wait to see how the other components will be built.

**Comment by tleunen** [comment]
I'll close this issue.. 
I refactored a bit some of the current components (should push everything later tonight).
I'll work on adding the missing components as well before 1.0.

**Comment by darkyen** [comment]
Awesome.

**Comment by darkyen** [comment]
Perfect :-)

**Comment by darkyen** [comment]
my latest commit just removed all of my custom code for your implementation :dart: the latest build is incredible.

**Comment by tleunen** [comment]
Thanks ;)

**Comment by darkyen** [comment]
Makes sense. 

MDL's tabs are pretty limited, and honestly tabs are hard to implement in a framework agnostic way (I personally have my own version of swipe tabs for android built using their styles)
