### ISSUE TITLE
Upgrade to MDL v1.0.6

### ISSUE THREAD

**Issue by fatbattk** [tleunen/react-mdl#103]
Would be awesome if project jumps from 1.0.4 to latest.

The last of the 1.0x version released yesterday.
https://github.com/google/material-design-lite/releases

**Comment by janpieterz** [comment]
This shouldn't be too difficult, besides that one fix to layout that is done locally, I think? 
I couldn't really find any breaking changes myself in their changelogs, but I might have overlooked it. If there are none given the HTML structure, it's basically upgrading to the new files, making sure the layout fix is applied, running the tests and that's it.

The layout fix, as far as I can see, is only this change: https://github.com/tleunen/material-design-lite/commit/b776c3e350b80756e82c97eb2dba8056886becf0

I'd be more than happy to take this one on, if you could provide some guidance @tleunen ? Mostly confirming my method described above.
I'd also like to be sure about the changes needed for the layout fix you've done not to regress. Perhaps I (or perhaps it's smarter that you do it since you know exactly what the fix does and how to detect it)  can write a test for it so we know with future upgrades it won't fall back?

Let me know what you think.

**Comment by tleunen** [comment]
Thanks @janpieterz for taking care of this. I was planning to do it today but you can definitely do it if you want ;)

There are no breaking changes in 1.0.6, it's only a patch version with a few fixes so it shouldn't be hard to update. And yes, you point to the right commit change.

There are no tests yet for the Layout component so everything should still work as before.

The problem it fixes is because `componentWillUnmount` was never called on any components inside a layout. The fix I suggested resolves that issue. But again, there are no tests yet to make sure it works as expected.

**Comment by janpieterz** [comment]
I'm having some trouble getting the right base to commit this from. Tried to pull a fork of your material-design-lite repository, checking out release, merging upstream remote back into it, but get way too much merge conflicts (all solvable, but it shouldn't be that hard). Merged release branch can be found here: https://github.com/janpieterz/material-design-lite/tree/release

There's a couple of options I see (new fork directly from Google, re-doing the specific changes to the layout) but there must be an easier way that I'm missing. I have never worked with forks from forks, and would like to make sure I don't fuck it up.

Sorry for the overhead I'm causing.

**Comment by tleunen** [comment]
I think it would be easier to get the latest version from upstream, and then re-apply the changes on top of it.
