### ISSUE TITLE
How to make footer not stay on screen in mobile view?

### ISSUE THREAD

**Issue by treeder** [tleunen/react-mdl#142]
The footer stays on the screen no matter what taking most of the real estate. Is there a way to keep it at the bottom?

**Comment by tleunen** [comment]
Thanks for reporting the issue @treeder. I checked and it's indeed an issue with our custom implementation of the layout

**Comment by tleunen** [comment]
Or maybe not. Where do you put the footer?
Because maybe you did the same mistake as I did. The footer should be inside `Content`, and not outside.

I know it's weird, but that's how the MDL team did it :/ Maybe they'll change that later with the refactoring of the layout in v2.

Can you confirm it's ok when putting the footer inside the content?
