### ISSUE TITLE
How to change direction of expandable input ?

### ISSUE THREAD

**Issue by darkyen** [tleunen/react-mdl#18]
Seems like the order of the elements in the expandable textfield decides which direction it will expand is there a switch to control this ?

**Comment by tleunen** [comment]
The order doesn't seem to impact the rendering.
I can see in the CSS that the icon is always aligned on the left.

You should create a ticket in the MDL repo to ask the team to create something to inverse the order.
What you could do also is update the position with CSS.

I'll close this since it's out of scope.

**Comment by darkyen** [comment]
Hmm i noticed it now, sorry about the false call x)
