### ISSUE TITLE
[v2] Rewrite Layout without mdlUpgrade

### ISSUE THREAD

**Issue by tleunen** [tleunen/react-mdl#295]
The `Layout` component is probably the biggest and the most complicated component in the material design lite library at the moment.
We should remove the need of the `mdlUpgrade` function on the Layout, and add what's needed for each component to be fully controlled with props.

**Comment by Download** [comment]
I've been thinking about this one a lot. My app has 2 drawers, one on the left hand side and one on the right. MDL's Layout component is a pain in this regard because it assumes you may have a left drawer but never a right one. I ended up using my own drawer component that is fully controlled.

Personally, I think in React MDL, the Layout should be *much* simpler. It shouldn't make so many assumptions about the components that can be nested inside it as it does now. 

E.g.

```html
<Layout fixedDrawer>
        <Drawer title="Title">
```

The `fixedDrawer` attribute is misplaced IMHO. It should have been:

```html
<Layout>
        <Drawer fixed title="Title">
```

What do you think about this? Any plans to make such more structural changes?

**Comment by tleunen** [comment]
It's definitely the way to go, but it can be hard to achieve now with the current css. `mdl-layout--fixed-drawer` is applied on the layout, not on the drawer :s

**Comment by Download** [comment]
Yeah I know. But honestly, the whole fixed thing isn't working very well i.c.w. React. Because they have all these responsive style rules that have a big impact on the structure. 

Are you in contact with them for their v2? I think they could use the feedback of where we have problems.
