### ISSUE TITLE
How can I centralize an element?

### ISSUE THREAD

**Issue by Natanael1234** [tleunen/react-mdl#321]
I found [this example](https://tleunen.github.io/react-mdl/templates/article/) but don't found any source code showing how to implement.

**Comment by Natanael1234** [comment]
Answer

		return (
			<DataTable       onClick = { onSelection } 
                                         **style={{width: '80%', margin: 'auto'}}**
			                 shadow  = { 0 	         }
			                 rows 	 = { cells       } >
			    <TableHeader name    = "id" 		       >Id 		    </TableHeader>
			    <TableHeader name    = "nome" 		     >Nome 		  </TableHeader>
			    <TableHeader name    = "endereco" 	   >Endereco  </TableHeader>
			    <TableHeader name    = "telefone" 	   >Telefone  </TableHeader>
			    <TableHeader name    = "acoes" 	       >Ações 		</TableHeader>
			    
			</DataTable>

,

**Comment by tleunen** [comment]
It really depends on what you want to center. Your datatable example will indeed work to center a datatable.

For the example you mention in the first post, the article template, this is done because it used the Grid system. There is a 2 empty columns sized before the "main" part. Also, this system allows to automatically hide the 2 first columns when the view is in a "mobile" or "tablet" mode, to keep 100% width.
