### ISSUE TITLE
Export utils to make it easier to make custom components

### ISSUE THREAD

**Issue by Pagebakers** [tleunen/react-mdl#67]
It would make life much easier if the utils were exported, so you can make custom mdl components.

What's your vision on this?

**Comment by faergeek** [comment]
Good idea :+1: .

I think that `mdlUpgrade` and `MDLComponent` should be a public API.

**Comment by tleunen** [comment]
Why would you want to create MDL components?

Every MDL components should be available in this repo. If something doesn't exists in MDL, you can probably create them using a simple basic React way instead of using the mdlUpgrade function.

**Comment by faergeek** [comment]
It's good for better customization, though, we can just leave note in readme about that, something like:
"If some feature is missing you can use MDLComponent/mdlUpgrade to temporarily recreate this functionality and don't forget to submit an issue :-)"

And give some example.
For example, I think that it should be possible to set custom tags everywhere.
Or I want to pass some props to some tag/component and I can't, because it's impossible in current implementation.

We should make that possible by making API public or by documenting how to achieve it (like documenting a hack).

**Comment by Pagebakers** [comment]
Awesome thanks!
