### ISSUE TITLE
Don't change event handling

### ISSUE THREAD

**Issue by joshq00** [tleunen/react-mdl#82]
```jsx
function myHandler ( event ) {}
<input type='checkbox' onChange={ myHandler } />
```

Then, if I were to switch to use this library,
```jsx
/* <input type='checkbox' onChange={ myHandler } /> */
<Checkbox onChange={ myHandler } />
```
it breaks.

It fires twice: once with the value, once with the Event.

I would much prefer to have my event handling all work the same: handle the event, let the handler work out what they find useful.

Please change to not intercept the native events.
Same request for Textfield and others.

Thanks for the library, by the way. It's so much easier than using all the mdl classnames

**Comment by faergeek** [comment]
Great point.

@tleunen What do you think? Why did you decide to pass value to handler instead of original event?

**Comment by faergeek** [comment]
Not sure that it's fired twice because of that though, AFAIK comments don't work like this in JSX.
@joshq00 Try removing it instead of commenting.

**Comment by joshq00** [comment]
That wasn't actual valid jsx.

What I mean is, 
if my code is
```jsx
handleChange ( arg ) {
   console.log( arg );
}
render () {
   return <Checkbox onChange={ this.handleChange } />
}
```

and I click the checkbox, the program will output 
```
true
SyntheticEvent
```

**Comment by joshq00** [comment]
Sorry for those repeated commits. Don't know if you expect one-commit merges. Had to do some tweaking tweaking with the demos

**Comment by joshq00** [comment]
If accepted, should probably bump a minor version... As these will be breaking changes

**Comment by tleunen** [comment]
@web2style once made a PR about the same kind of change: https://github.com/tleunen/react-mdl/pull/25. It was accepted and then reverted.

But this one seems to be more consistant. It updates every component with the same behavior.

Initially, the reason why the value was only sent is because usually, that's the only information you care to receive. But I do understand sometimes you want more, or like in this case, you want the same function signature. So I agree to accept the PR. I'll do it later after a better look at it.
