### ISSUE TITLE
Contributing: use implicit attr=true

### ISSUE THREAD

**Issue by joshq00** [tleunen/react-mdl#90]
Want to open discussion on using the implicit attr=true syntax

Example:
```jsx
<Button raised accent disabled>
// vs
<Button raised={ true } accent={ true } disabled={ true }>
```

As HTML generally accepts the former, and is much less verbose, I think having the implicit form would be appropriate

**Comment by faergeek** [comment]
:+1:

**Comment by joshq00** [comment]
Another reason I can see this being very useful is, when doing a quick code scan, singling out `true` vs `false` will be much easier.

```jsx
<Button colored={ true } ripple={ false } accent={ true }>
// vs
<Button colored ripple={ false } accent>
```

If changed, a separate discussion is whether "true" should be the default value for anything. Considering `<Button ripple>` makes it very clear that we are _adding_ functionality rather than `<Button ripple={ false }>` to turn it off

**Comment by tleunen** [comment]
I agree with removing the boolean values in jsx. I was forcing them in personal projects but the more I use them, the more I want them removed as well.

But yes, it would mean that all booleans should be false by default.
The only one that isn't false is the `ripple` effect, because I think people usually add it since it's part of the MDL so I thought I could save that to users

**Comment by tleunen** [comment]
I did a first step which removes the boolean when it's true. I'll change the default for the ripple later.
