### ISSUE TITLE
Feature request - Build Meteor package

### ISSUE THREAD

**Issue by VenelinPetkov** [tleunen/react-mdl#92]
Hi,
I would love to see this project directly intergarted with meteor.

**Comment by tleunen** [comment]
Never used Meteor, what would be the impact? What need to be done to be integrated with meteor?

**Comment by generalleger** [comment]
@VenelinPetkov did you try to import the npm package?

@tleunen usually npm packages integrate pretty easily with Meteor, since Meteor can require npm packages the same way vanilla node projects can.  But, some packages integrate better than others.  Some work without any modification, and others need to be tuned for Meteor's  environment.

The challenges with google mdl and Meteor are described here: https://atmospherejs.com/zodiase/mdl

**Comment by tleunen** [comment]
So is there anything we can do to make it easier maybe? @generalleger

**Comment by generalleger** [comment]
@tleunen Someone with some time just needs to try it and see how easily they integrate and where the issues are.

**Comment by darkyen** [comment]
If React works nice with meteor so this https://github.com/reactjs/react-meteor should be helpful, As mentioned in the project itself React is agnostic of the way you fetch data from the server and meteor can be easily dropped in for that part.

**Comment by generalleger** [comment]
@darkyen Meteor has built in support for React without using that package.  You can simply do `meteor add react`

**Comment by darkyen** [comment]
@generalleger I think that is the official package that meteor installs when you do meteor add react (since its by react team)

**Comment by generalleger** [comment]
@darkyen I think this is what they add...  https://github.com/meteor/react-packages

**Comment by darkyen** [comment]
even better :D from meteor team +1

**Comment by tleunen** [comment]
Meteor supports React (see http://react-in-meteor.readthedocs.org/en/latest/) so this shouldn't be an issue anymore.
